# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5f31fa40362c2fbf11a7675b418707308ebcd2b85eb2ac261f2177951f1a06f3aea1d3586cc62e402b6cb2ad1fa5ddd440a3e05311e51f13dff13097f0f30dcf

test:
  secret_key_base: b055336cf2418de11b39b59a70dd7cccc75d4432eb97b3c6d0dbdf94bba8e8003b750ce05cf53c49fe712f8449414ad4fec5c239a10d2bb380260d46042ee48a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
